# Permalinks
permalink:           pretty

# Setup
title:               Stan Kamil Jastrzebski
url:                 http://kudkudak.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Stan Kamil Jastrzebski
  url:               https://twitter.com/kudkudakp
  email:             staszek.jastrzebski@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
